
stages:
  - release

create_release:
  stage: release
  image: konstanta.gitlab.yandexcloud.net:5050/konstanta-it/infrastructure/onec-docker:1.1.5
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - oscript ${CI_PROJECT_DIR}/.gitlab/scripts/1script/create_release.os
